Repository Baghdad-Squad/Novix, pull requests merged in 2025-07, with the labels that each got.

#25 Feature/#3 implement design system foundations
  build.gradle.kts
  design_system/build.gradle.kts
  design_system/src/main/java/com/baghdad/design_system/.keep
  design_system/src/main/java/com/baghdad/design_system/color/model/NovixColor.kt
  design_system/src/main/java/com/baghdad/design_system/color/theme/darkThemeColor.kt
  design_system/src/main/java/com/baghdad/design_system/color/theme/lightThemeColor.kt
  design_system/src/main/java/com/baghdad/design_system/textStyle/model/NovixTextStyle.kt
  design_system/src/main/java/com/baghdad/design_system/textStyle/theme/defaultTextStyle.kt
  design_system/src/main/java/com/baghdad/design_system/theme/NovixTheme.kt
  design_system/src/main/java/com/baghdad/design_system/theme/Theme.kt
  design_system/src/main/res/font/ibm_plex_sans_medium.ttf
  design_system/src/main/res/font/ibm_plex_sans_regular.ttf
  design_system/src/main/res/font/ibm_plex_sans_semibold.ttf
  gradle/libs.versions.toml
Labels: blocking

#207 Feature/#175 implement app navigation
  app/src/main/java/com/baghdad/novix/MainActivity.kt
  ui/build.gradle.kts
  ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt
  ui/src/main/java/com/baghdad/ui/navigation/NovixNavHost.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/DummyScreen.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/actorDetails/ActorDetailsNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/actorDetails/ActorDetailsNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/authentication/AuthenticationNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/authentication/AuthenticationNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/categories/CategoriesNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/categories/CategoriesNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/home/HomeNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/home/HomeNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/movieDetails/MovieDetailsNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/movieDetails/MovieDetailsNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/myAccount/MyAccountNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/myAccount/MyAccountNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/myLists/MyListsNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/myLists/MyListsNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/onBoarding/OnBoardingNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/onBoarding/OnBoardingNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/reviews/ReviewsNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/reviews/ReviewsNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/search/SearchNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/search/SearchNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/tvShowDetails/TvShowDetailsNavEvent.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/tvShowDetails/TvShowDetailsNavGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/graph/util/ToGraph.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/ActorDetailsRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/AuthenticationRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/CategoriesRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/Graph.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/HomeRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/MovieDetailsRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/MyAccountRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/MyListsRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/OnBoardingRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/ReviewsRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/Route.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/SearchRoute.kt
  ui/src/main/java/com/baghdad/ui/navigation/route/TvShowDetailsRoute.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/search/SearchScreenEffect.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/search/SearchViewModel.kt
Labels: blocking

#228 Fix:/#225 clear all button to delete the all recent viewed not recent search
  ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt
Labels: bug

#233 Feature/#190 implement scaffold
  design_system/src/main/java/com/baghdad/design_system/component/Scaffold.kt
Labels: question, blocking

#268 Fix/#263 review screen issues
  design_system/src/main/res/drawable/ic_empty_review_screen.xml
  entity/src/main/java/com/baghdad/entity/media/Review.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt
  repository/src/main/java/com/baghdad/repository/model/ReviewDto.kt
  ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
  viewmodel/src/main/java/com/baghdad/viewmodel/review/ReviewInteractionListener.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/review/ReviewMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/review/ReviewScreenState.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/review/ReviewViewModel.kt
Labels: bug

#405 Fix/#400 click on sign up and forget password return the user directly to login when the is language arabic
  ui/src/main/java/com/baghdad/ui/feature/authentication/ForgetPasswordWebViewScreen.kt
  ui/src/main/java/com/baghdad/ui/feature/authentication/SignUpWebViewScreen.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: bug

#463 Fix/#418 fix tv show details screen
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/episode/EpisodeDetailsResponseMapper.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/episode/EpisodeResponseMapper.kt
  ui/src/main/java/com/baghdad/ui/feature/search/component/filter/FilterBottomSheet.kt
  ui/src/main/java/com/baghdad/ui/feature/topRating/TopRatingScreen.kt
  ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/TvShowDetailsScreen.kt
  ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt
  ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/TvShowDetailsCard.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
  viewmodel/src/main/java/com/baghdad/viewmodel/topRating/TopRatingViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/tvShowDetails/TvShowDetailsMapper.kt
Labels: bug

#417 Fix/#416 fix actor details screen
  entity/src/main/java/com/baghdad/entity/person/Actor.kt
  local_datasource/src/main/java/com/baghdad/local_datasource/roomDB/entity/Actor.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/actor/ActorDetailsResponseMapper.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/actor/CastMemberDtoMapper.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/actor/PopularPeopleMapper.kt
  remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/search/ActorSearchResponseMapper.kt
  remote_datasource/src/test/java/com/baghdad/remoteDataSource/mapper/actor/PopularPeopleMapperKtTest.kt
  repository/src/main/java/com/baghdad/repository/mapper/ActorMapper.kt
  repository/src/main/java/com/baghdad/repository/model/ActorDto.kt
  ui/src/main/java/com/baghdad/ui/feature/actorDetails/component/ActorCardDetails.kt
  ui/src/main/java/com/baghdad/ui/feature/actorDetails/component/CardInfo.kt
  ui/src/main/java/com/baghdad/ui/feature/actorDetails/component/GallerySection.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/actorDetails/ActorDetailsMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/actorDetails/ActorDetailsScreenState.kt
Labels: bug

#413 Fix/#399 fix trending movies screen bugs
  app/src/main/java/com/baghdad/novix/di/ViewModelModule.kt
  design_system/src/main/java/com/baghdad/design_system/component/Tab.kt
  ui/src/main/java/com/baghdad/ui/feature/trendingMovies/TrendingMoviesScreen.kt
  ui/src/main/java/com/baghdad/ui/feature/trendingTvShow/TrendingTvShowScreen.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/base/BaseViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/movie/TrendingMoviesMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesEffect.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesInteractionListener.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesScreenState.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingTvShow/TrendingTvShowViewModel.kt
Labels: bug

#415 Fix/#402 fix continue watching screen bugs
  ui/src/main/java/com/baghdad/ui/feature/continueWatching/ContinueWatchingScreen.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingState.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingViewModel.kt
Labels: bug

#452 Fix/#445 card in carousel row top rating and continue watching is not clipped no radius
  design_system/src/main/java/com/baghdad/design_system/component/HorizontalCarousel.kt
  ui/src/main/java/com/baghdad/ui/feature/component/HomeCard.kt
  ui/src/main/java/com/baghdad/ui/feature/home/component/ContinueWatchingSection.kt
  ui/src/main/java/com/baghdad/ui/feature/home/component/HomeHorizontalCarouselSection.kt
  ui/src/main/java/com/baghdad/ui/feature/home/component/TopRatingSection.kt
  ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt
Labels: bug

#453 Fix: fix button state when it's loading
  design_system/src/main/java/com/baghdad/design_system/component/button/FloatingActionButton.kt
  design_system/src/main/java/com/baghdad/design_system/component/button/NegativeButton.kt
  design_system/src/main/java/com/baghdad/design_system/component/button/OutlinedButton.kt
  design_system/src/main/java/com/baghdad/design_system/component/button/PrimaryButton.kt
  design_system/src/main/java/com/baghdad/design_system/component/button/TextButton.kt
Labels: bug

#462 Fix/#430 preserve TextField cursor position when restoring query
  design_system/src/main/java/com/baghdad/design_system/component/TextField.kt
Labels: bug

#504 fix/#484-fix-when-click-on-the-same-section-it-will-reload
  viewmodel/src/main/java/com/baghdad/viewmodel/topRating/TopRatingViewModel.kt
Labels: bug
