Repository Baghdad-Squad/Novix, pull requests merged in 2025-08, with the labels that each got.

#582 HotFix/#580 fix unit tests
  app/src/main/java/com/baghdad/novix/di/ViewModelModule.kt
  domain/src/androidTest/java/com/baghdad/domain/ExampleInstrumentedTest.kt
  domain/src/test/java/com/baghdad/domain/usecase/search/SearchMoviesUseCaseTest.kt
  domain/src/test/java/com/baghdad/domain/usecase/search/SearchTvShowsUseCaseTest.kt
  domain/src/test/java/com/baghdad/domain/util/SearchFilterHelperTest.kt
  gradle/libs.versions.toml
  viewmodel/build.gradle.kts
  viewmodel/src/main/java/com/baghdad/viewmodel/categoryMovies/CategoryMoviesViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/categoryTvShows/CategoryTvShowsViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/login/LoginViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/review/ReviewViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/topTvShowPicks/TopTvShowPicksViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingTvShow/TrendingTvShowViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/tvShowDetails/TvShowDetailsViewModel.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/categoryMovies/CategoryMoviesViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/categoryTvShows/CategoryTvShowsViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/login/LoginViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/main/MainEffectTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/main/MainStateTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/main/MainViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/review/ReviewViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/trendingMovie/TrendingMovieMapperTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/trendingMovie/TrendingMoviesViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/trendingTvShow/TrendingTvShowViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/utls/CollectAndSnapshot.kt
Labels: blocking

#589 Fix/#584 should add movie or tv show when open trailer not when open tv show or movie deatils
  ui/src/main/java/com/baghdad/ui/feature/movieDetails/MovieDetailsScreen.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/movieDetails/MovieDetailsInteractionListener.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/tvShowDetails/TvShowDetailsViewModel.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/movieDetils/MovieDetailsViewModelTest.kt
Labels: bug

#720 Fix: logout button not respond and not Dismissed
  ui/src/main/java/com/baghdad/ui/feature/profile/component/ProfileHeaderWithOptions.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/profile/ProfileViewModel.kt
Labels: bug

#726 Fix/#709 fix season number
  ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeHeaderWithDetailsCard.kt
  ui/src/main/java/com/baghdad/ui/util/EpisodeTitle.kt
  ui/src/main/res/values-ar/strings.xml
  ui/src/main/res/values/strings.xml
Labels: bug

#738 Fix:/#706 all bugs in episode details screen
  ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeDetailsHeader.kt
  ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/TvShowDetailsScreen.kt
  ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsScreenState.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/tvShowDetails/TvShowDetailsMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/tvShowDetails/TvShowDetailsScreenState.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/util/DateTimeUtil.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/util/DurationUtil.kt
Labels: bug

#812 Refactor/#810 TopTvShowPicks
  ui/src/main/java/com/baghdad/ui/feature/topTvShowPicks/TopTvShowPicksScreen.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/topTvShowPicks/TopTvShowPicksMapper.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/topTvShowPicks/TopTvShowPicksViewModel.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/mapper/TopTvShowPicksMapperTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/topTvShowPicks/MockTvShow.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/topTvShowPicks/TopTvShowPicksMapperKtTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/topTvShowPicks/TopTvShowPicksViewModelTest.kt
Labels: enhancement

#809 Refactor/#807 trending actor viewmodel with testcases
  ui/src/main/java/com/baghdad/ui/feature/component/ActorCard.kt
  ui/src/main/java/com/baghdad/ui/feature/trendingActors/TrendingActorsScreen.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingActors/TrendingActorViewModel.kt
  viewmodel/src/main/java/com/baghdad/viewmodel/trendingActors/TrendingActorsMapper.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/trendingActor/TrendingActorViewModelTest.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/trendingActor/TrendingActorsMapperKtTest.kt
Labels: enhancement

#900 Refactor/ #879 Profile
  viewmodel/src/main/java/com/baghdad/viewmodel/profile/ProfileViewModel.kt
  viewmodel/src/test/java/com/baghdad/viewmodel/profile/ProfileViewModelTest.kt
Labels: enhancement

#933 Fix/#932 fix hidden border in card
  design_system/src/main/java/com/baghdad/design_system/component/CartegoryCard.kt
  design_system/src/main/res/font/ibm_plex_sans_medium.ttf
  design_system/src/main/res/font/ibm_plex_sans_regular.ttf
  design_system/src/main/res/font/ibm_plex_sans_semibold.ttf
  ui/src/main/java/com/baghdad/ui/feature/component/ActorCard.kt
Labels: bug
